const functions = require("firebase-functions");
const admin = require("firebase-admin");
const PDFDocument = require("pdfkit");
const axios = require("axios");
// const sharp = require("sharp"); // NATIVE CRASH PREVENTION
const path = require('path');
const os = require('os');
const fs = require('fs');

admin.initializeApp();

const mmToPt = (mm) => mm * 2.835;

/**
 * HELPER: Download Image to Disk (Stream)
 * Returns the file path
 */
const downloadToDisk = async (url, destPath) => {
    // ABORT CONTROLLER for Aggressive Timeout
    const controller = new AbortController();
    const timeout = setTimeout(() => {
        controller.abort();
    }, 10000); // 10 Seconds HARD STOP

    try {
        const writer = fs.createWriteStream(destPath);
        const response = await axios({
            url,
            method: 'GET',
            responseType: 'stream',
            signal: controller.signal
        });

        response.data.pipe(writer);

        return new Promise((resolve, reject) => {
            writer.on('finish', () => {
                clearTimeout(timeout);
                resolve(true);
            });
            writer.on('error', (err) => {
                console.error("Stream writer error:", err);
                try { writer.close(); fs.unlinkSync(destPath); } catch (e) { }
                resolve(false);
            });
        });
    } catch (error) {
        clearTimeout(timeout);
        // Don't log "canceled" as error, it's expected
        if (axios.isCancel(error) || error.code === 'ECONNABORTED') {
            console.warn(`TIMEOUT/CANCEL: Image took too long: ${url}`);
        } else {
            console.warn("Download failed:", url, error.message);
        }
        return false;
    }
};

/**
 * HELPER: Process Image from Disk
 * Input: File Path
 * Output: Buffer (Optimized)
 */
const processImageFromDisk = async (filePath) => {
    try {
        // PURE JS MODE: Just read the file.
        // PDFKit handles JPEGs native.
        return fs.readFileSync(filePath);
    } catch (error) {
        console.warn("Disk reading failed:", error);
        return null;
    }
};

// HELPER: Draw Header
const drawHeader = (doc, company, currentZone, isContinuation, margin, pageWidth) => {
    const headerTop = margin;
    const rightMargin = pageWidth - margin;

    doc.save();
    doc.fontSize(14).font('Helvetica-Bold').fillColor('#0f172a');
    doc.text((company.commercialName || company.name).toUpperCase(), margin, headerTop);

    doc.fontSize(8).font('Helvetica-Bold').fillColor('#2563eb');
    doc.text('REPORTE FOTOGRÁFICO', margin, headerTop + 2, { align: 'right', width: pageWidth - (margin * 2) });

    doc.fontSize(6).font('Helvetica').fillColor('#64748b');
    doc.text('REVISIÓN E INVENTARIO', margin, headerTop + 12, { align: 'right', width: pageWidth - (margin * 2) });

    doc.lineWidth(0.5).strokeColor('#e2e8f0').moveTo(margin, headerTop + 25).lineTo(rightMargin, headerTop + 25).stroke();

    let cursorY = headerTop + 35;
    const badgeText = isContinuation ? "ZONA (CONTINUACIÓN)" : "ZONA ACTUAL";
    const badgeWidth = doc.widthOfString(badgeText, { fontSize: 7 }) + 8;

    doc.roundedRect(margin, cursorY, badgeWidth, 12, 2).fill('#0f172a');
    doc.fillColor('white').fontSize(7).font('Helvetica-Bold').text(badgeText, margin + 4, cursorY + 2);

    doc.fillColor('#0f172a').fontSize(14).font('Helvetica-Bold')
        .text(`ZONA: ${currentZone}`.toUpperCase(), margin, cursorY + 16);

    doc.restore();
    return cursorY + 40;
};

// HELPER: Draw Footer
const drawFooter = (doc, company, margin, pageHeight, pageWidth) => {
    const footerY = pageHeight - margin + 5;
    const contentWidth = pageWidth - (margin * 2);

    doc.save();
    doc.lineWidth(0.5).strokeColor('#e2e8f0').moveTo(margin, footerY - 10).lineTo(pageWidth - margin, footerY - 10).stroke();
    doc.fontSize(6).font('Helvetica').fillColor('#94a3b8');
    doc.text(`CONFIDENCIAL - ${(company.commercialName || company.name).toUpperCase()} - ${new Date().getFullYear()}`, margin, footerY);
    doc.text('REPORTE GENERADO INTERNAMENTE', margin, footerY, { align: 'right', width: contentWidth });
    doc.restore();
};

/**
 * TRIGGER: onFolderStatusChange
 * Listens for status changes to 'FINALIZADO'
 * Executes the PDF Generation Pipeline
 */
// TRIGGER DISABLED (Moved to Client-Side)
const DISABLED_onFolderStatusChange = functions.runWith({
    timeoutSeconds: 540, // 9 Mins Max
    memory: '4GB'       // Max Memory for Safety
}).firestore.document('users/{uid}/companies/{companyId}').onUpdate(async (change, context) => {

    const before = change.before.data();
    const after = change.after.data();

    // 0. GUARD: If PDF is already provided (Client-Side Generation), DO NOTHING.
    if (after.finalPdfUrl) {
        console.log("PDF already generated by client. Skipping Cloud Function.");
        return null;
    }

    // 1. CHECKS
    const isFinalizing = after.status === 'FINALIZADO';
    const isRetry = after.status === 'RETRY_PDF';

    if (!isRetry && !isFinalizing) return null;
    if (!isRetry && before.status === 'FINALIZADO' && after.finalPdfUrl) return null;

    console.log(`[START] PDF Generation for ${context.params.companyId} (Mode: ${after.status})`);

    const company = after;
    const items = company.checklists || [];
    const uid = context.params.uid;
    const inventoryId = context.params.companyId;

    const MARGIN = mmToPt(10);
    const PAGE_WIDTH = mmToPt(210);
    const PAGE_HEIGHT = mmToPt(297);
    const CONTENT_WIDTH = PAGE_WIDTH - (MARGIN * 2);
    const BOTTOM_Safe_Limit = PAGE_HEIGHT - MARGIN - mmToPt(20);

    // 1. SETUP DISK STREAM
    const fileName = `${inventoryId}_${Date.now()}.pdf`;
    const tempPdfPath = path.join(os.tmpdir(), fileName);
    const writeStream = fs.createWriteStream(tempPdfPath);

    const doc = new PDFDocument({
        size: 'A4',
        margin: MARGIN,
        autoFirstPage: false,
        autoAddPages: false
    });

    doc.pipe(writeStream);

    doc.on('pageAdded', () => {
        drawFooter(doc, company, MARGIN, PAGE_HEIGHT, PAGE_WIDTH);
    });

    try {
        // 2. COVER PAGE (Using Disk for Safety too)
        doc.addPage();

        // Custom Cover Color
        if (company.reportColor) {
            doc.rect(0, 0, PAGE_WIDTH, PAGE_HEIGHT).fill(company.reportColor);
        } else {
            doc.rect(0, 0, PAGE_WIDTH, PAGE_HEIGHT).fill('#1e293b'); // Default Slate-900
        }

        let cursorY = MARGIN;

        // LOGO
        if (company.logoUrl) {
            const logoPath = path.join(os.tmpdir(), `logo_${Date.now()}.jpg`);
            if (await downloadToDisk(company.logoUrl, logoPath)) {
                try {
                    // Safe Mode: Draw directly from disk buffer (No Sharp)
                    doc.image(logoPath, MARGIN, cursorY, { height: mmToPt(25), fit: [mmToPt(60), mmToPt(25)], align: 'left' });
                } catch (err) { console.error("Logo draw error", err); }
                try { fs.unlinkSync(logoPath); } catch (e) { }
            }
        }
        cursorY += mmToPt(35);

        doc.lineWidth(4).strokeColor('white').moveTo(MARGIN, cursorY).lineTo(MARGIN + 50, cursorY).stroke();
        cursorY += 10;
        doc.fontSize(10).font('Helvetica').fillColor('#cbd5e1').text('REPORTE FOTOGRÁFICO', MARGIN, cursorY);
        cursorY += 15;
        doc.fontSize(24).font('Helvetica-Bold').fillColor('white').text((company.commercialName || company.name).toUpperCase(), MARGIN, cursorY);
        cursorY += 40;

        // FACADE
        if (company.facadePhotoUrl) {
            const facadePath = path.join(os.tmpdir(), `facade_${Date.now()}.jpg`);
            if (await downloadToDisk(company.facadePhotoUrl, facadePath)) {
                try {
                    // Safe Mode: Raw Buffer
                    const rawBuffer = fs.readFileSync(facadePath);
                    doc.image(rawBuffer, MARGIN, cursorY, { width: CONTENT_WIDTH, height: mmToPt(120), fit: [CONTENT_WIDTH, mmToPt(120)], align: 'center', valign: 'center' });
                } catch (err) { console.error("Facade draw error", err); }
                try { fs.unlinkSync(facadePath); } catch (e) { }
            } else {
                doc.roundedRect(MARGIN, cursorY, CONTENT_WIDTH, mmToPt(120), 4).fill('#334155');
            }
            cursorY += mmToPt(120) + 20;
        }

        doc.roundedRect(MARGIN, cursorY, CONTENT_WIDTH, 60, 4).fill('white');
        doc.fillColor('#0f172a').fontSize(12).font('Helvetica-Bold').text((company.legalName || 'Razón Social').toUpperCase(), MARGIN + 15, cursorY + 15);
        doc.fillColor('#64748b').fontSize(9).font('Helvetica').text((company.address || 'Ubicación').toUpperCase(), MARGIN + 15, cursorY + 35);


        // 3. ITEMS LOOP (OPTIMIZED BATCH PROCESSING - SAFE MODE)
        const activeZones = [...new Set(items.map(i => i.location))].sort();

        for (const zone of activeZones) {
            const zoneItems = items.filter(i => i.location === zone);

            // A. GATHER ALL PHOTOS FOR THIS ZONE
            const zonePhotos = [];
            for (const item of zoneItems) {
                if (item.photos && item.photos.length) {
                    item.photos.filter(Boolean).forEach(url => {
                        zonePhotos.push({ url, item });
                    });
                }
            }

            // B. BATCH PROCESS PHOTOS (CONCURRENCY: 5)
            // We map URL -> Local Filtered Path
            const photoPathMap = new Map(); // url -> localPath
            const BATCH_SIZE = 5;

            for (let i = 0; i < zonePhotos.length; i += BATCH_SIZE) {
                const batch = zonePhotos.slice(i, i + BATCH_SIZE);
                await Promise.all(batch.map(async (p) => {
                    // Unique Temp file
                    const tempImgPath = path.join(os.tmpdir(), `z_${zone.replace(/\W/g, '')}_${Math.random().toString(36).substr(2, 9)}.jpg`);
                    try {
                        if (await downloadToDisk(p.url, tempImgPath)) {
                            // SAFE MODE: Just verify existence, map path. No processing.
                            photoPathMap.set(p.url, tempImgPath);
                        }
                    } catch (e) {
                        console.error("Batch error for url:", p.url, e);
                    }
                }));
            }

            // C. BUILD PDF PAGES FOR THIS ZONE (Synchronous-like using local files)
            doc.addPage();
            cursorY = drawHeader(doc, company, zone, false, MARGIN, PAGE_WIDTH);
            doc.lineWidth(2).strokeColor('#2563eb').moveTo(MARGIN, cursorY).lineTo(PAGE_WIDTH - MARGIN, cursorY).stroke();
            cursorY += 20;

            for (const item of zoneItems) {
                const titleHeight = 25;
                const notesHeight = item.notes ? doc.heightOfString(item.notes, { width: CONTENT_WIDTH, fontSize: 9 }) + 10 : 0;

                const photos = (item.photos || []).filter(Boolean);
                let columns = 3;
                if (photos.length === 1) columns = 1;
                else if (photos.length === 2) columns = 2;
                else if (photos.length === 4) columns = 2;

                const GAP = 10;
                const boxWidth = (CONTENT_WIDTH - (GAP * (columns - 1))) / columns;
                const aspectRatio = 0.85;
                const boxHeight = boxWidth * aspectRatio;

                // Page Break Check (Header)
                let firstRowHeight = (photos.length > 0) ? boxHeight : 0;
                if (cursorY + titleHeight + notesHeight + firstRowHeight > BOTTOM_Safe_Limit) {
                    doc.addPage();
                    cursorY = drawHeader(doc, company, zone, true, MARGIN, PAGE_WIDTH);
                    doc.lineWidth(2).strokeColor('#2563eb').moveTo(MARGIN, cursorY).lineTo(PAGE_WIDTH - MARGIN, cursorY).stroke();
                    cursorY += 20;
                    drawFooter(doc, company, MARGIN, PAGE_HEIGHT, PAGE_WIDTH);
                }

                // Draw Item Header
                doc.rect(MARGIN, cursorY, 4, 14).fill('#2563eb');
                doc.fillColor('#0f172a').fontSize(10).font('Helvetica-Bold').text(`TIPO: ${item.name.toUpperCase()}`, MARGIN + 10, cursorY + 2);
                doc.lineWidth(0.5).strokeColor('#e2e8f0').moveTo(MARGIN, cursorY + 18).lineTo(PAGE_WIDTH - MARGIN, cursorY + 18).stroke();
                cursorY += 25;

                if (item.notes) {
                    doc.fillColor('#475569').fontSize(9).font('Helvetica-Oblique').text(item.notes, MARGIN, cursorY, { width: CONTENT_WIDTH });
                    cursorY += notesHeight;
                }

                // DRAW PHOTOS (Using Pre-processed Paths)
                if (photos.length > 0) {
                    let photoIndex = 0;
                    while (photoIndex < photos.length) {
                        if (cursorY + boxHeight > BOTTOM_Safe_Limit) {
                            doc.addPage();
                            cursorY = drawHeader(doc, company, zone, true, MARGIN, PAGE_WIDTH);
                            doc.lineWidth(2).strokeColor('#2563eb').moveTo(MARGIN, cursorY).lineTo(PAGE_WIDTH - MARGIN, cursorY).stroke();
                            cursorY += 20;
                            drawFooter(doc, company, MARGIN, PAGE_HEIGHT, PAGE_WIDTH);
                        }

                        // Process Row
                        for (let col = 0; col < columns && photoIndex < photos.length; col++) {
                            const x = MARGIN + (col * (boxWidth + GAP));
                            const url = photos[photoIndex];

                            const localPath = photoPathMap.get(url);

                            if (localPath && fs.existsSync(localPath)) {
                                try {
                                    doc.save();
                                    doc.roundedRect(x, cursorY, boxWidth, boxHeight, 4).clip();
                                    // SAFE MODE: Draw directly from disk
                                    doc.image(localPath, x, cursorY, { fit: [boxWidth, boxHeight], align: 'center', valign: 'center' });
                                    doc.restore();
                                    doc.roundedRect(x, cursorY, boxWidth, boxHeight, 4).strokeColor('#e2e8f0').lineWidth(0.5).stroke();
                                } catch (err) {
                                    console.error(`Error drawing image ${url}:`, err);
                                }
                            }
                            // Else: Image failed to download/process, just skip or draw placeholder? Skipping for now.

                            photoIndex++;
                        }
                        cursorY += boxHeight + GAP;
                    }
                }
                cursorY += 15;
            }

            // D. CLEANUP ZONE FILES IMMEDIATELY
            for (const localPath of photoPathMap.values()) {
                if (fs.existsSync(localPath)) {
                    try { fs.unlinkSync(localPath); } catch (e) { }
                }
            }
        }

        doc.end();

        await new Promise((resolve, reject) => {
            writeStream.on('finish', resolve);
            writeStream.on('error', reject);
        });

        // 4. UPLOAD
        console.log("[UPLOAD] Starting upload...");
        const bucket = admin.storage().bucket();
        const destination = `reports/${uid}/${inventoryId}_FINAL.pdf`;

        await bucket.upload(tempPdfPath, {
            destination: destination,
            metadata: { contentType: 'application/pdf' }
        });

        fs.unlinkSync(tempPdfPath); // Cleanup PDF

        const file = bucket.file(destination);
        const [url] = await file.getSignedUrl({
            action: 'read',
            expires: '01-01-2100',
        });

        console.log(`[DONE] PDF Generation Successful: ${url}`);

        // 5. UPDATE FIRESTORE (Success)
        await change.after.ref.update({
            status: 'FINALIZADO',
            finalPdfUrl: url,
            updatedAt: admin.firestore.FieldValue.serverTimestamp() // Important to update timestamp
        });

        return { success: true };

    } catch (globalError) {
        console.error("FATAL ERROR IN PDF GENERATION:", globalError);
        // Reset status to ERROR so user can retry
        await change.after.ref.update({
            status: 'ERROR',
            errorLog: globalError.message
        });
        return { success: false };
    }
});

// --- AI BLUEPRINT GENERATOR (New Architecture) ---
// 1. Initialize Gemini
const { GoogleGenerativeAI } = require("@google/generative-ai");

// Access API Key from Environment Variables
// RUN: firebase functions:config:set google.api_key="YOUR_API_KEY"
const genAI = new GoogleGenerativeAI(process.env.GOOGLE_API_KEY || functions.config().google?.api_key || "DEMO_KEY");

exports.generateBlueprint = functions.https.onCall(async (data, context) => {
    // 1. Auth Check
    if (!context.auth) {
        throw new functions.https.HttpsError('unauthenticated', 'User must be logged in.');
    }

    const { projectId } = data;
    if (!projectId) {
        throw new functions.https.HttpsError('invalid-argument', 'projectId is required.');
    }

    try {
        console.log(`[AI-BLUEPRINT] Generating for Project: ${projectId}`);

        // 2. Fetch Project Data
        const docRef = admin.firestore().collection('users').doc(context.auth.uid).collection('companies').doc(projectId);
        const docSnap = await docRef.get();

        if (!docSnap.exists) {
            throw new functions.https.HttpsError('not-found', 'Project not found.');
        }

        const projectData = docSnap.data();
        const zonesRaw = projectData.locations || []; // Assuming 'locations' stores the zones list
        const inventoryRaw = projectData.checklists || []; // Assuming 'checklists' stores items

        // 3. Prepare Data for AI (Clean & Simplistic)
        const categories = {};

        // Group Inventory by Zone
        const inventoryByZone = {};
        inventoryRaw.forEach(item => {
            const zName = item.location || 'General';
            if (!inventoryByZone[zName]) inventoryByZone[zName] = [];

            // Simplify Item Data
            inventoryByZone[zName].push({
                name: item.name,
                type: item.type || 'equipment', // 'extintor', 'botiquin', etc.
                qty: item.quantity || 1
            });
        });

        // Prepare Zone List
        // If no locations exist, infer them from inventory or default to a single rectangular room
        let zonesForPrompt = zonesRaw.map(z => z.name || z);
        if (zonesForPrompt.length === 0) {
            zonesForPrompt = Object.keys(inventoryByZone).length > 0 ? Object.keys(inventoryByZone) : ['Área General'];
        }

        // 4. CONSTRUCT "PROMPT MAESTRO"
        const model = genAI.getGenerativeModel({ model: "gemini-1.5-flash" });

        const prompt = `
        ACT AS AN EXPERT ARCHITECT.
        GOAL: Generate a JSON blueprint for a technical floor plan.
        CONTEXT: A commercial establishment with the following zones and inventory.
        
        ZONES: ${JSON.stringify(zonesForPrompt)}
        INVENTORY: ${JSON.stringify(inventoryByZone)}
        
        RULES:
        1. CANVAS: 800x600.
        2. LAYOUT: Place zones logically.
           - "Kitchen/Cocina" must be at the back/corner.
           - "Entrance/Recepcion" must be at the bottom (y close to 600).
           - "Bathrooms/Baños" at edges.
           - "Storage/Bodega" at back.
           - No floating zones. Use the full space (minimize gaps).
           - Walls should be aligned.
        3. PLACEMENT:
           - Place inventory items INSIDE their respective zones.
           - "Extintor" near walls.
           - "Salida" near doors.
        4. STRUCTURE:
           - Return ONLY valid JSON. No markdown. No chatter.
           - Format:
             {
               "width": 800,
               "height": 600,
               "outer_wall": "path string describing perimeter",
               "zones": [
                 { "id": "z1", "name": "Cocina", "x": 0, "y": 0, "w": 200, "h": 200, "type": "service" }
               ],
               "items": [
                 { "name": "Extintor", "x": 10, "y": 10, "zone_id": "z1" }
               ]
             }
        `;

        // 5. CALL AI
        const result = await model.generateContent(prompt);
        const response = await result.response;
        const text = response.text();

        // 6. CLEAN & PARSE JSON
        // Remove markdown code blocks if present
        const jsonStr = text.replace(/```json/g, '').replace(/```/g, '').trim();
        const blueprint = JSON.parse(jsonStr);

        return { success: true, blueprint };

    } catch (error) {
        console.error("[AI-BLUEPRINT] Error:", error);
        throw new functions.https.HttpsError('internal', error.message);
    }
});
